### PR TITLE
Windows fix #2

### LINKED ISSUE #2: [🐛BUG] Incorrect paths on windows
When running on windows the plugin fails to escape the backslashes of the filepath leading to an error.
The path given to the router is also wrong.
```log
[vite] Internal server error: Failed to resolve import "G:sourceRepossolid-pokedoutespokemon" from "..\..\..\@vite-plugin-pages\generated-pages-solid". Does the file exist?
  Plugin: vite:import-analysis
  File: /@vite-plugin-pages/generated-pages-solid
  1  |  import {lazy} from "solid-js";
  2  |  const routes = [{ path: "/g:\source\repos\solid-pokedex-test\src\routes\pokemon", component: lazy(() => import("G:\source\Repos\solid-pokedex-test\src\routes\pokemon"))},
     |                                                                                                                 ^
  3  |  ];
  4  |  
```
Reproduction:

1. Clone <https://github.com/N0tExisting/solid-pokedex.git> onto a windows machine.
2. Update `src/App.tsx` like so:
```diff
import type { Component } from 'solid-js';
import { Link as A, useRoutes } from 'solid-app-router';
import { Meta } from 'solid-meta';
-//import routes from 'virtual:generated-pages-solid';
+import routes from 'virtual:generated-pages-solid';
-import routes from './routes';
+//import routes from './routes';
import { Toggle } from './components/DarkMode';
import { Boundary } from './errors/Boundary';

const App: Component = () => {
```

3. Run vite dev server
4. Load the page
5. See Error

### PR DESCRIPTION
**Pull request by N0tExisting**
### Changes in this PR:
- Fix #2
- Add Changelog
- Add Ability to add different Multi-Routes
- Fix _(Most)_ tests.

### Needed changes:
- Fix `generate.spec.ts`

### CODE REVIEW

**Comment by aldy505** [comment]
the test fails because the object's items order is non-deterministic, one temporary solution is to do a deep sort to the object and then test it against the result.

or just move back to jest again and use snapshot testing, which was originally what the project used, but I think it's a bit too much for something like this.

**Comment by N0tExisting** [comment]
> the test fails because the object's items order is non-deterministic, one temporary solution is to do a deep sort to the object and then test it against the result.
> 
> or just move back to jest again and use snapshot testing, which was originally what the project used, but I think it's a bit too much for something like this.

@aldy505
1. I mean that I don't know why [this](https://github.com/N0tExisting/vite-plugin-pages-solid/runs/4342351779?check_suite_focus=true#step:5:20) is failing.
2. Yeah, jest is probably overkill, should I try [AVA](https://github.com/avajs/ava/blob/main/docs/04-snapshot-testing.md)?

**Comment by aldy505** [comment]
1. yes, it's because the order of object's values are non-deterministic, even if it's all good in your machine, doesn't mean it's also fine on others.
2. yeah sure!

**Comment by N0tExisting** [comment]
> 1. yes, it's because the order of object's values are non-deterministic, even if it's all good in your machine, doesn't mean it's also fine on others.

It also doesn't work on my machine, but I can't see the issue with the diff

**Comment by N0tExisting** [comment]
I finally Fixed the tests (on windows).

Also snapshots wouldn't work, because They are different depending on the os, and the location of the files.

**Comment by N0tExisting** [comment]
@aldy505 This can now be merged.

**Comment by aldy505** [comment]
I'll check it later tonight

**Review by aldy505 — APPROVED** [review]
there are some commented out console.logs, but that's okay. I'll clean it up and release this to npm in a few hours.

thanks for the contribution!

**Comment by N0tExisting** [comment]
> there are some commented out console.logs, but that's okay. I'll clean it up and release this to npm in a few hours.

Most of the logs should be within the tests, incase you need to redo the fixtures / snapshots.

**Pull request merged**
